// <auto-generated />
using System;
using Circlimate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Circlimate.Data.Migrations
{
    [DbContext(typeof(CirclimateDbContext))]
    [Migration("20251211041105_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Circlimate.Data.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("city_name");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double?>("MaxTemperatureC")
                        .HasColumnType("double precision")
                        .HasColumnName("max_temperature_c");

                    b.Property<double?>("MinTemperatureC")
                        .HasColumnType("double precision")
                        .HasColumnName("min_temperature_c");

                    b.Property<DateTime?>("NewestDataDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("newest_data_date");

                    b.Property<DateTime?>("OldestDataDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("oldest_data_date");

                    b.HasKey("CityId");

                    b.HasIndex("CityName")
                        .HasDatabaseName("idx_cities_name");

                    b.HasIndex("CityName", "Latitude", "Longitude")
                        .IsUnique()
                        .HasDatabaseName("uq_city_location");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("Circlimate.Data.Entities.TemperatureDataEntity", b =>
                {
                    b.Property<long>("TemperatureDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("temperature_data_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TemperatureDataId"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("MaxTemperatureC")
                        .HasColumnType("double precision")
                        .HasColumnName("max_temperature_c");

                    b.Property<double>("MinTemperatureC")
                        .HasColumnType("double precision")
                        .HasColumnName("min_temperature_c");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.HasKey("TemperatureDataId");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("idx_temperature_provider");

                    b.HasIndex("CityId", "RecordDate")
                        .HasDatabaseName("idx_temperature_city_date");

                    b.HasIndex("CityId", "RecordDate", "ProviderId")
                        .IsUnique()
                        .HasDatabaseName("uq_city_date_provider");

                    b.ToTable("temperature_data");
                });

            modelBuilder.Entity("Circlimate.Data.Entities.TemperatureDataEntity", b =>
                {
                    b.HasOne("Circlimate.Data.Entities.City", "City")
                        .WithMany("TemperatureData")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Circlimate.Data.Entities.City", b =>
                {
                    b.Navigation("TemperatureData");
                });
#pragma warning restore 612, 618
        }
    }
}
